export const Constants = {
  WIDTH: 800,
  HEIGHT: 600,
  FIELDS_HEIGHT: 25,

  TIMEOUT_CONNECTING: 10000,
  TIMEOUT_KEEPALIVE: 5000,
  TIMEOUT_DROP: 30000,

  GLOBAL_PORT: 23761,
  DEFAULT_PORT: 6112,
  PUBLIC_ROOM_PORT: 28842,

  DUMMY_NAME: "23E(S_%24%40)!Xc",

  START_GAME_DELAY: 5000,
  EMPTY_ROOM_CLOSE_DELAY: 30000,
  TURN_TIME: 60000,

  MAX_PLAYERS: 10,
  MAX_SOLDIERS_PER_PLAYER: 4,
  MAX_CLIENTS: 10,
  INITIAL_NUM_SOLDIERS: 2,
  MAXIMUM_COLOR_MODULE_SQUARED: 3 * 160 * 160,

  TEAM1: 1,
  TEAM2: 2,

  NORMAL_FUNC: 0,
  FST_ODE: 1,
  SND_ODE: 2,

  PLANE_LENGTH: 770,
  PLANE_HEIGHT: 450,
  PLANE_GAME_LENGTH: 50,

  CIRCLE_MEAN_RADIUS: 40,
  CIRCLE_STANDARD_DEVIATION: 25,
  NUM_CIRCLES_MEAN_VALUE: 15,
  NUM_CIRCLES_STANDARD_DEVIATION: 7,

  SOLDIER_RADIUS: 7,
  SOLDIER_SELECTION_RADIUS: 15,
  SOLDIER_ANIMATION_DELAY_STANDARD_DEVIATION: 5000,
  SOLDIER_ANIMATION_MEAN_VALUE: 3000,
  SOLDIER_MAX_DEATH_TIME: 6000,
  NAME_FADE_TIME: 1000,

  EXPLOSION_RADIUS: 12,

  FUNCTION_VELOCITY: 1500,
  FUNC_FADE_TIME: 1000,
  NEXT_TURN_DELAY: 3000,

  FUNC_MAX_STEPS: 20000,
  FUNC_MAX_STEP_DISTANCE_SQUARED: 0.001,
  FUNC_MIN_X_STEP_DISTANCE: 0.00001,
  STEP_SIZE: 0.01,

  ANGLE_STEP_MIN: Math.PI / (20 * 360),
  ANGLE_STEP_MAX: 0.03,
  ANGLE_FACTOR: 1.2,
  ANGLE_ERROR: Math.PI / 360,
  MAX_ANGLE_LOOPS: 100,
  ANGLE_ACCELERATION: 0.000003,

  RANDOM_TREE_MAX_RAND: 1000,
  RANDOM_TREE_VALUE_VARIABLE_CHANCE: 900,
  RANDOM_TREE_ONE_PARAMETER_CHANCE: 500,
  MAX_AI_RANDOM_DOUBLE: 100,
  NODE_MUTATION_CHANCE: 750,
  MAX_AI_TIME: 2,

  NUM_FUNCTIONS_AI: 50,
  NUM_FUNCTIONS_UNCHANGED_TURN_AI: 5,
  NUM_FUNCTION_MUTATED_AI: 25,
  RANDOM_FUNC_MEAN_LENGTH: 10,
  RANDOM_FUNC_VALUE_CHANCE: 0.5,
  RANDOM_FUNC_VARIABLE_CHANCE: 0.5,
  RANDOM_FUNC_VALUE_MEAN: 10.2,
  RANDOM_FUNC_MEAN_CROSSOVER_LENGTH: 5,
  RANDOM_FUNC_MEAN_MUTATION_LENGTH: 5,

  computerNames: [
    "Deep Thought",
    "HAL",
    "Skynet",
    "Agent Smith",
    "Multivac",
    "Deep Blue",
    "Cleverbot",
    "Alpha Zordon",
    "Wolfram",
  ],

  COMPUTER_LEVEL_STANDARD_DEVIATION: 40,
  COMPUTER_LEVEL_MEAN_VALUE: 50,
  COMPUTER_LEVEL_MIN_VALUE: 10,

  NONE: 0,
  PRE_GAME: 1,
  GAME: 2,

  MAIN_MENU_SCREEN: 0,
  PRE_GAME_SCREEN: 1,
  GLOBAL_ROOM_SCREEN: 2,
  GAME_SCREEN: 3,
  NUM_SCREENS: 4,
} as const;

export type GameMode = typeof Constants.NORMAL_FUNC | typeof Constants.FST_ODE | typeof Constants.SND_ODE;
export type GameState = 0 | 1 | 2;